name: Django CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Tests
              run: |
                  python dactions/manage.py test
            - name: Success Notification
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                    INCOMING_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              with:
                    text: ":heavy_check_mark: Build success - Deploy -  Server - TEST - Azure Web pps CI/CD. :heavy_check_mark:"